CREATE TYPE public.company_role AS ENUM ('owner','buyer','supplier','verifier','finance');
CREATE TYPE public.order_status AS ENUM ('draft','contracted','in_progress','delivered','verifying','revision_requested','verification_inconclusive','accepted','settled','cancelled','expired');
CREATE TYPE public.verification_decision AS ENUM ('approved','rejected','inconclusive','error');
CREATE TYPE public.integration_status AS ENUM ('connected','pending','error');

CREATE TABLE public.profiles (id uuid PRIMARY KEY, display_name text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role; ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_user_id uuid, name text NOT NULL, slug text NOT NULL UNIQUE, description text NOT NULL, kind text NOT NULL, is_demo boolean NOT NULL DEFAULT false, operational boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.companies TO authenticated; GRANT SELECT ON public.companies TO anon; GRANT ALL ON public.companies TO service_role; ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.company_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, user_id uuid NOT NULL, role public.company_role NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id,user_id,role));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.company_members TO authenticated; GRANT ALL ON public.company_members TO service_role; ALTER TABLE public.company_members ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.company_role NOT NULL, UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role; ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid,_role public.company_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role)$$;
CREATE OR REPLACE FUNCTION public.is_company_member(_company_id uuid,_user_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$SELECT EXISTS(SELECT 1 FROM public.company_members WHERE company_id=_company_id AND user_id=_user_id) OR EXISTS(SELECT 1 FROM public.companies WHERE id=_company_id AND owner_user_id=_user_id)$$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid,public.company_role) TO authenticated; GRANT EXECUTE ON FUNCTION public.is_company_member(uuid,uuid) TO authenticated;

CREATE TABLE public.agents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, name text NOT NULL, agent_type text NOT NULL, model text NOT NULL, instructions text NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.agents TO authenticated; GRANT ALL ON public.agents TO service_role; ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.capabilities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, code text NOT NULL, name text NOT NULL, description text NOT NULL, executor_type text NOT NULL, integration_status public.integration_status NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id,code));
GRANT SELECT,INSERT,UPDATE,DELETE ON public.capabilities TO authenticated; GRANT SELECT ON public.capabilities TO anon; GRANT ALL ON public.capabilities TO service_role; ALTER TABLE public.capabilities ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.offers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, capability_id uuid NOT NULL REFERENCES public.capabilities(id), title text NOT NULL, published boolean NOT NULL DEFAULT false, current_version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.offers TO authenticated; GRANT SELECT ON public.offers TO anon; GRANT ALL ON public.offers TO service_role; ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.offer_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), offer_id uuid NOT NULL REFERENCES public.offers(id) ON DELETE CASCADE, version integer NOT NULL, description text NOT NULL, required_inputs jsonb NOT NULL DEFAULT '[]', output_format jsonb NOT NULL DEFAULT '{}', price_units integer NOT NULL CHECK(price_units>0), deadline_hours integer NOT NULL CHECK(deadline_hours>0), acceptance_criteria jsonb NOT NULL, revision_limit integer NOT NULL DEFAULT 1 CHECK(revision_limit>=0), cancellation_policy text NOT NULL, available boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(offer_id,version));
GRANT SELECT,INSERT ON public.offer_versions TO authenticated; GRANT SELECT ON public.offer_versions TO anon; GRANT ALL ON public.offer_versions TO service_role; ALTER TABLE public.offer_versions ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, available_units integer NOT NULL DEFAULT 0 CHECK(available_units>=0), reserved_units integer NOT NULL DEFAULT 0 CHECK(reserved_units>=0), paid_units integer NOT NULL DEFAULT 0 CHECK(paid_units>=0), received_units integer NOT NULL DEFAULT 0 CHECK(received_units>=0), commission_units integer NOT NULL DEFAULT 0 CHECK(commission_units>=0), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.accounts TO authenticated; GRANT SELECT ON public.accounts TO anon; GRANT ALL ON public.accounts TO service_role; ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), buyer_company_id uuid NOT NULL REFERENCES public.companies(id), supplier_company_id uuid REFERENCES public.companies(id), offer_id uuid REFERENCES public.offers(id), title text NOT NULL, brief jsonb NOT NULL DEFAULT '{}', budget_cap_units integer NOT NULL CHECK(budget_cap_units>0), status public.order_status NOT NULL DEFAULT 'draft', selected_reason text, current_delivery_version integer NOT NULL DEFAULT 0, revision_count integer NOT NULL DEFAULT 0, is_demo boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.orders TO authenticated; GRANT SELECT ON public.orders TO anon; GRANT ALL ON public.orders TO service_role; ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.contracts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL UNIQUE REFERENCES public.orders(id), offer_version_id uuid NOT NULL REFERENCES public.offer_versions(id), buyer_company_id uuid NOT NULL REFERENCES public.companies(id), supplier_company_id uuid NOT NULL REFERENCES public.companies(id), price_units integer NOT NULL, commission_bps integer NOT NULL DEFAULT 1000, deadline_at timestamptz NOT NULL, order_data jsonb NOT NULL, acceptance_criteria jsonb NOT NULL, revision_limit integer NOT NULL, cancellation_policy text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.contracts TO authenticated; GRANT SELECT ON public.contracts TO anon; GRANT ALL ON public.contracts TO service_role; ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES public.orders(id), kind text NOT NULL, provider text NOT NULL, external_job_id text, idempotency_key text NOT NULL UNIQUE, status text NOT NULL, error_message text, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.jobs TO authenticated; GRANT SELECT ON public.jobs TO anon; GRANT ALL ON public.jobs TO service_role; ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES public.orders(id), version integer NOT NULL, submitted_by_company_id uuid NOT NULL REFERENCES public.companies(id), storage_path text NOT NULL, file_name text NOT NULL, media_type text NOT NULL, byte_size bigint NOT NULL CHECK(byte_size>0), sha256 text, test_upload boolean NOT NULL DEFAULT false, supplier_message text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(order_id,version));
GRANT SELECT,INSERT ON public.deliveries TO authenticated; GRANT SELECT ON public.deliveries TO anon; GRANT ALL ON public.deliveries TO service_role; ALTER TABLE public.deliveries ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.verification_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES public.orders(id), delivery_id uuid NOT NULL UNIQUE REFERENCES public.deliveries(id), delivery_version integer NOT NULL, rules_version text NOT NULL, tool_name text NOT NULL, checks jsonb NOT NULL, decision public.verification_decision NOT NULL, summary text NOT NULL, verified_by_user_id uuid, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT ON public.verification_reports TO authenticated; GRANT SELECT ON public.verification_reports TO anon; GRANT ALL ON public.verification_reports TO service_role; ALTER TABLE public.verification_reports ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.ledger_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id), order_id uuid REFERENCES public.orders(id), entry_type text NOT NULL, amount_units integer NOT NULL CHECK(amount_units>0), idempotency_key text NOT NULL UNIQUE, description text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.ledger_entries TO authenticated; GRANT SELECT ON public.ledger_entries TO anon; GRANT ALL ON public.ledger_entries TO service_role; ALTER TABLE public.ledger_entries ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.order_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES public.orders(id), actor_type text NOT NULL, actor_label text NOT NULL, event_type text NOT NULL, result text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.order_events TO authenticated; GRANT SELECT ON public.order_events TO anon; GRANT ALL ON public.order_events TO service_role; ALTER TABLE public.order_events ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.inference_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES public.companies(id), order_id uuid REFERENCES public.orders(id), task_type text NOT NULL, model_requested text NOT NULL, status text NOT NULL, duration_ms integer, usage_data jsonb, error_message text, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.inference_runs TO authenticated; GRANT ALL ON public.inference_runs TO service_role; ALTER TABLE public.inference_runs ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.integrations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES public.companies(id), provider text NOT NULL, status public.integration_status NOT NULL DEFAULT 'pending', last_checked_at timestamptz, safe_message text NOT NULL, UNIQUE(company_id,provider));
GRANT SELECT ON public.integrations TO authenticated; GRANT SELECT ON public.integrations TO anon; GRANT ALL ON public.integrations TO service_role; ALTER TABLE public.integrations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profiles_self_select" ON public.profiles FOR SELECT TO authenticated USING(id=auth.uid()); CREATE POLICY "profiles_self_insert" ON public.profiles FOR INSERT TO authenticated WITH CHECK(id=auth.uid()); CREATE POLICY "profiles_self_update" ON public.profiles FOR UPDATE TO authenticated USING(id=auth.uid()) WITH CHECK(id=auth.uid());
CREATE POLICY "companies_demo_anon" ON public.companies FOR SELECT TO anon USING(is_demo); CREATE POLICY "companies_member_select" ON public.companies FOR SELECT TO authenticated USING(is_demo OR public.is_company_member(id,auth.uid())); CREATE POLICY "companies_owner_insert" ON public.companies FOR INSERT TO authenticated WITH CHECK(owner_user_id=auth.uid()); CREATE POLICY "companies_owner_update" ON public.companies FOR UPDATE TO authenticated USING(owner_user_id=auth.uid()) WITH CHECK(owner_user_id=auth.uid());
CREATE POLICY "members_select" ON public.company_members FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_company_member(company_id,auth.uid())); CREATE POLICY "members_owner_manage" ON public.company_members FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM public.companies c WHERE c.id=company_id AND c.owner_user_id=auth.uid())) WITH CHECK(EXISTS(SELECT 1 FROM public.companies c WHERE c.id=company_id AND c.owner_user_id=auth.uid()));
CREATE POLICY "roles_self" ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid());
CREATE POLICY "agents_members" ON public.agents FOR ALL TO authenticated USING(public.is_company_member(company_id,auth.uid())) WITH CHECK(public.is_company_member(company_id,auth.uid()));
CREATE POLICY "capabilities_anon" ON public.capabilities FOR SELECT TO anon USING(EXISTS(SELECT 1 FROM public.companies c WHERE c.id=company_id AND c.is_demo)); CREATE POLICY "capabilities_auth" ON public.capabilities FOR SELECT TO authenticated USING(true); CREATE POLICY "capabilities_owner" ON public.capabilities FOR ALL TO authenticated USING(public.is_company_member(company_id,auth.uid())) WITH CHECK(public.is_company_member(company_id,auth.uid()));
CREATE POLICY "offers_anon" ON public.offers FOR SELECT TO anon USING(published); CREATE POLICY "offers_auth" ON public.offers FOR SELECT TO authenticated USING(published OR public.is_company_member(company_id,auth.uid())); CREATE POLICY "offers_owner" ON public.offers FOR ALL TO authenticated USING(public.is_company_member(company_id,auth.uid())) WITH CHECK(public.is_company_member(company_id,auth.uid()));
CREATE POLICY "offer_versions_anon" ON public.offer_versions FOR SELECT TO anon USING(EXISTS(SELECT 1 FROM public.offers o WHERE o.id=offer_id AND o.published)); CREATE POLICY "offer_versions_auth" ON public.offer_versions FOR SELECT TO authenticated USING(true); CREATE POLICY "offer_versions_owner_insert" ON public.offer_versions FOR INSERT TO authenticated WITH CHECK(EXISTS(SELECT 1 FROM public.offers o WHERE o.id=offer_id AND public.is_company_member(o.company_id,auth.uid())));
CREATE POLICY "accounts_anon" ON public.accounts FOR SELECT TO anon USING(EXISTS(SELECT 1 FROM public.companies c WHERE c.id=company_id AND c.is_demo)); CREATE POLICY "accounts_auth" ON public.accounts FOR SELECT TO authenticated USING(public.is_company_member(company_id,auth.uid()) OR EXISTS(SELECT 1 FROM public.companies c WHERE c.id=company_id AND c.is_demo));
CREATE POLICY "orders_anon" ON public.orders FOR SELECT TO anon USING(is_demo); CREATE POLICY "orders_auth" ON public.orders FOR SELECT TO authenticated USING(is_demo OR public.is_company_member(buyer_company_id,auth.uid()) OR public.is_company_member(supplier_company_id,auth.uid()) OR public.has_role(auth.uid(),'verifier')); CREATE POLICY "orders_buyer_insert" ON public.orders FOR INSERT TO authenticated WITH CHECK(public.is_company_member(buyer_company_id,auth.uid()));
CREATE POLICY "contracts_anon" ON public.contracts FOR SELECT TO anon USING(EXISTS(SELECT 1 FROM public.orders o WHERE o.id=order_id AND o.is_demo)); CREATE POLICY "contracts_auth" ON public.contracts FOR SELECT TO authenticated USING(public.is_company_member(buyer_company_id,auth.uid()) OR public.is_company_member(supplier_company_id,auth.uid()) OR public.has_role(auth.uid(),'verifier'));
CREATE POLICY "jobs_anon" ON public.jobs FOR SELECT TO anon USING(EXISTS(SELECT 1 FROM public.orders o WHERE o.id=order_id AND o.is_demo)); CREATE POLICY "jobs_auth" ON public.jobs FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.orders o WHERE o.id=order_id AND (o.is_demo OR public.is_company_member(o.buyer_company_id,auth.uid()) OR public.is_company_member(o.supplier_company_id,auth.uid()))));
CREATE POLICY "deliveries_anon" ON public.deliveries FOR SELECT TO anon USING(EXISTS(SELECT 1 FROM public.orders o WHERE o.id=order_id AND o.is_demo)); CREATE POLICY "deliveries_auth" ON public.deliveries FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.orders o WHERE o.id=order_id AND (o.is_demo OR public.is_company_member(o.buyer_company_id,auth.uid()) OR public.is_company_member(o.supplier_company_id,auth.uid()) OR public.has_role(auth.uid(),'verifier')))); CREATE POLICY "deliveries_supplier_insert" ON public.deliveries FOR INSERT TO authenticated WITH CHECK(public.is_company_member(submitted_by_company_id,auth.uid()));
CREATE POLICY "reports_anon" ON public.verification_reports FOR SELECT TO anon USING(EXISTS(SELECT 1 FROM public.orders o WHERE o.id=order_id AND o.is_demo)); CREATE POLICY "reports_auth" ON public.verification_reports FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.orders o WHERE o.id=order_id AND (o.is_demo OR public.is_company_member(o.buyer_company_id,auth.uid()) OR public.is_company_member(o.supplier_company_id,auth.uid()) OR public.has_role(auth.uid(),'verifier')))); CREATE POLICY "reports_verifier_insert" ON public.verification_reports FOR INSERT TO authenticated WITH CHECK(public.has_role(auth.uid(),'verifier') AND verified_by_user_id=auth.uid());
CREATE POLICY "ledger_anon" ON public.ledger_entries FOR SELECT TO anon USING(EXISTS(SELECT 1 FROM public.companies c WHERE c.id=company_id AND c.is_demo)); CREATE POLICY "ledger_auth" ON public.ledger_entries FOR SELECT TO authenticated USING(public.is_company_member(company_id,auth.uid()) OR EXISTS(SELECT 1 FROM public.companies c WHERE c.id=company_id AND c.is_demo));
CREATE POLICY "events_anon" ON public.order_events FOR SELECT TO anon USING(EXISTS(SELECT 1 FROM public.orders o WHERE o.id=order_id AND o.is_demo)); CREATE POLICY "events_auth" ON public.order_events FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.orders o WHERE o.id=order_id AND (o.is_demo OR public.is_company_member(o.buyer_company_id,auth.uid()) OR public.is_company_member(o.supplier_company_id,auth.uid()) OR public.has_role(auth.uid(),'verifier'))));
CREATE POLICY "inference_auth" ON public.inference_runs FOR SELECT TO authenticated USING(company_id IS NULL OR public.is_company_member(company_id,auth.uid()));
CREATE POLICY "integrations_anon" ON public.integrations FOR SELECT TO anon USING(company_id IS NULL); CREATE POLICY "integrations_auth" ON public.integrations FOR SELECT TO authenticated USING(company_id IS NULL OR public.is_company_member(company_id,auth.uid()));

CREATE OR REPLACE FUNCTION public.prevent_immutable_changes() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'record is immutable'; END$$;
CREATE TRIGGER contracts_immutable BEFORE UPDATE OR DELETE ON public.contracts FOR EACH ROW EXECUTE FUNCTION public.prevent_immutable_changes(); CREATE TRIGGER deliveries_immutable BEFORE UPDATE OR DELETE ON public.deliveries FOR EACH ROW EXECUTE FUNCTION public.prevent_immutable_changes(); CREATE TRIGGER reports_immutable BEFORE UPDATE OR DELETE ON public.verification_reports FOR EACH ROW EXECUTE FUNCTION public.prevent_immutable_changes(); CREATE TRIGGER ledger_immutable BEFORE UPDATE OR DELETE ON public.ledger_entries FOR EACH ROW EXECUTE FUNCTION public.prevent_immutable_changes();

CREATE INDEX idx_offers_company ON public.offers(company_id); CREATE INDEX idx_orders_companies ON public.orders(buyer_company_id,supplier_company_id); CREATE INDEX idx_events_order_created ON public.order_events(order_id,created_at); CREATE INDEX idx_deliveries_order_version ON public.deliveries(order_id,version);