/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiA2aSplatRouteImport } from './routes/api/a2a/$'
import { Route as ApiPublicOpenapiRouteImport } from './routes/api/public/openapi'
import { Route as ApiReviewsOrderIdChatCompletionsRouteImport } from './routes/api/reviews/$orderId/chat/completions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA2aSplatRoute = ApiA2aSplatRouteImport.update({
  id: '/api/a2a/$',
  path: '/api/a2a/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenapiRoute = ApiPublicOpenapiRouteImport.update({
  id: '/api/public/openapi',
  path: '/api/public/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsOrderIdChatCompletionsRoute =
  ApiReviewsOrderIdChatCompletionsRouteImport.update({
    id: '/api/reviews/$orderId/chat/completions',
    path: '/api/reviews/$orderId/chat/completions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/studio': typeof StudioRoute
  '/api/a2a/$': typeof ApiA2aSplatRoute
  '/api/public/openapi': typeof ApiPublicOpenapiRoute
  '/api/reviews/$orderId/chat/completions': typeof ApiReviewsOrderIdChatCompletionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/studio': typeof StudioRoute
  '/api/a2a/$': typeof ApiA2aSplatRoute
  '/api/public/openapi': typeof ApiPublicOpenapiRoute
  '/api/reviews/$orderId/chat/completions': typeof ApiReviewsOrderIdChatCompletionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/studio': typeof StudioRoute
  '/api/a2a/$': typeof ApiA2aSplatRoute
  '/api/public/openapi': typeof ApiPublicOpenapiRoute
  '/api/reviews/$orderId/chat/completions': typeof ApiReviewsOrderIdChatCompletionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/studio'
    | '/api/a2a/$'
    | '/api/public/openapi'
    | '/api/reviews/$orderId/chat/completions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/studio'
    | '/api/a2a/$'
    | '/api/public/openapi'
    | '/api/reviews/$orderId/chat/completions'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/studio'
    | '/api/a2a/$'
    | '/api/public/openapi'
    | '/api/reviews/$orderId/chat/completions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  StudioRoute: typeof StudioRoute
  ApiA2aSplatRoute: typeof ApiA2aSplatRoute
  ApiPublicOpenapiRoute: typeof ApiPublicOpenapiRoute
  ApiReviewsOrderIdChatCompletionsRoute: typeof ApiReviewsOrderIdChatCompletionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a2a/$': {
      id: '/api/a2a/$'
      path: '/api/a2a/$'
      fullPath: '/api/a2a/$'
      preLoaderRoute: typeof ApiA2aSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openapi': {
      id: '/api/public/openapi'
      path: '/api/public/openapi'
      fullPath: '/api/public/openapi'
      preLoaderRoute: typeof ApiPublicOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/$orderId/chat/completions': {
      id: '/api/reviews/$orderId/chat/completions'
      path: '/api/reviews/$orderId/chat/completions'
      fullPath: '/api/reviews/$orderId/chat/completions'
      preLoaderRoute: typeof ApiReviewsOrderIdChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  StudioRoute: StudioRoute,
  ApiA2aSplatRoute: ApiA2aSplatRoute,
  ApiPublicOpenapiRoute: ApiPublicOpenapiRoute,
  ApiReviewsOrderIdChatCompletionsRoute: ApiReviewsOrderIdChatCompletionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
